name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - mkdocs.yml

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip install \
            mkdocs-material~=9.0.11 \
            mkdocs-awesome-pages-plugin~=2.8.0 \
            mkdocs-include-markdown-plugin~=4.0.3

      - run: mkdocs gh-deploy --force
